### ISSUE TITLE
This project is cloned from Flashbots ; should add attribution and compatible license

### ISSUE THREAD

**Issue by metachris** [pon-pbs/pon-relay#2]
Friendly shoutout from Flashbots: since this repository is a clone from our https://github.com/flashbots/mev-boost-relay please add correct and responsible attribution and a compatible license.

**Comment by pon-pbs** [comment]
@metachris , 
license and attribution requests updated

**Comment by metachris** [comment]
In particular, the Flashbots mev-boost-relay codebase is AGPL licensed, which is not compatible with republishing it in this repository under the MIT license.
