### ISSUE TITLE
Correct license and attribution are still not in place

### ISSUE THREAD

**Issue by metachris** [pon-pbs/pon-relay#5]
Continuation of #2 because it was closed prematurely.

**The license and attribution are still not in place.**

**1. Licensing**

The Flashbots mev-boost-relay codebase is AGPL licensed, which is not compatible with republishing it in this repository under the MIT license. Please update the license of this project to a valid license, or don't build on top of the Flashbots mev-boost-relay codebase.

**2. Attribution**

Since this is just a direct fork from https://github.com/flashbots/mev-boost-relay, I think it's irresponsible to scrub the commit history as you have done and present the commit history as coming only from you: https://github.com/pon-pbs/pon-relay/commits/main -- this is not great open-source collaboration. You should keep the original commits by the original authors, and also mark this project as a fork of the Flashbots relay codebase.

**Comment by pon-pbs** [comment]
Software in question was an experiment and no longer in use. Thank you.
